version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: postgres
      POSTGRES_DB: mini_amazon
    restart: always
  # server:
  #   build: ./server
  #   user: root
  #   volumes:
  #     - ./server:/code
  #   command: bash -c "./run.sh"
  #   ports:
  #     - "12345:12345"
  #   expose:
  #     - "12345"
  #   depends_on:
  #     - db

  web-init:
    build: ./web-app
    command: bash -c "./wait-for-it.sh db:5432 --strict -- ./initserver.sh"
    volumes:
      - ./web-app:/code
    depends_on:
      - db
  web:
    build: ./web-app
    user: nobody
    command: /code/runserver.sh
    volumes:
      - ./web-app:/code
    expose:
      - "8000"
    depends_on:
      - web-init
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    depends_on:
      - web
volumes:
  data-volume:
