# Generated by Django 4.0.1 on 2022-04-18 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(max_length=1000)),
                ('catalog', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('packId', models.IntegerField(primary_key=True, serialize=False)),
                ('addrX', models.IntegerField()),
                ('addrY', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PACKING', 'packing'), ('PACKED', 'packed'), ('LOADING', 'loading'), ('LOADED', 'loaded'), ('DELIVERING', 'delivering'), ('DELIVERED', 'delivered')], default='packing', max_length=50)),
                ('amount', models.IntegerField()),
                ('upsId', models.IntegerField()),
                ('price', models.FloatField(max_length=1000)),
                ('version', models.IntegerField(default=1)),
                ('itemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon.item')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemAmount', models.IntegerField()),
                ('whID', models.IntegerField()),
                ('version', models.IntegerField(default=1)),
                ('itemId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazon.item')),
            ],
            options={
                'db_table': 'Inventory',
                'unique_together': {('itemId', 'whID')},
            },
        ),
    ]
