# Generated by Django 4.0.1 on 2022-04-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('addrX', models.CharField(max_length=10, null=True)),
                ('addrY', models.CharField(max_length=10, null=True)),
                ('upsID', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
