# Generated by Django 4.0.1 on 2022-04-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='itemAmount',
            new_name='item_amount',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='itemId',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='whID',
            new_name='wh_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemId',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='addrX',
            new_name='addr_x',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='addrY',
            new_name='addr_y',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='itemId',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='packId',
            new_name='pack_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='upsId',
            new_name='ups_id',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('item_id', 'wh_id')},
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
