# Generated by Django 4.0.4 on 2022-04-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pack_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
