# Generated by Django 4.0.4 on 2022-04-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_alter_item_item_id_alter_order_pack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='version',
            field=models.IntegerField(),
        ),
    ]
