# Generated by Django 4.0.4 on 2022-04-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_alter_inventory_version_alter_item_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catalog',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
